name = "backend"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-18"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
